### ISSUE TITLE
Directories with spaces and forced cropping

### ISSUE THREAD

**Issue by mackerski** [cliffordsnow/roav_uploader#6]
Hi - it looks like you've saved me a whack of work by writing this before I had to. I encountered some initial difficulties due to having a space in my file paths. I have progressively fixed this, and I'll share this work once I can be sure I've caught all cases.

I'm curious on one point - whether or not I use the crop option, some crop of the raw video frame is made. In fact I kind of wanted to build some kind of cropping into my workflow - enough to chop off the Dashcam's branded data panel at the bottom, and the bottom of my image has plenty of the bonnet of my car that isn't so useful. But at the top (maybe) and the sides, I don't really want to lose that content. I can easily rejig what you've done, but I'm curious as to the original motivation.

Finally, I find that the resulting jpegs are pretty full of artefacts and generally lacking a bunch of detail that is present in still frames from the video. I'll probe more deeply into why that might be, but do you have any thoughts?

**Comment by cliffordsnow** [comment]
I have plenty of space (now) using a 250gb sd card to do the processing on. It could be simplified by just using the jpeg space instead of coping the final result to the output file. I did this to help in building the app to see where things were going wrong. 

About cropping - In my car, even with the ROAV mounted high in the windshield, it still captures the bonnet and do to its wide angle shot, both sides of my windshield. Originally I was cropping the video for upload. That takes a long long time. 

Regarding artifacts, here is an [uploaded image](https://openstreetcam.org/details/1445034/29/track-info) after all the cropping. I'll look to see if I can find the original video to grab a screenshot of the still, but the video is likely overwritten by now. I definitely loose a good portion of the video from the cropping.

**Comment by mackerski** [comment]
I have a solution on artefacts - ffmpeg has a flag that permits the jpeg compression to be controlled. Due to the smallish size of the frames and the fact that both Mapillary and OSC probably post-process the images themselves, I've gone for max quality:

		ffmpeg -i ${dir}/${video}.MP4 -ss 00:00:01 -t ${frames} -r 1 -vf "crop=1280:630:0:0" -qscale:v 1 jpeg/${video_no}_%03d.jpeg

(it's the -r 1 part)

Here you'll also see what I did for cropping - in my case, due to how my dashcam is mounted, I want to keep the top and sides, but lose a bunch off the bottom where the branded instrumentation and my car bonnet are.

I wonder whether having the crop preference come from the config file might be a good way of catering for all needs. I've seen that the ffmpeg crop flags allow for values to be, for instance, fractions of actual dimensions, so instead of the in-script detection of frame dimensions, it should be possible to ask for a crop width of, say, 90%, of the true frame width.

**Comment by cliffordsnow** [comment]
I agree that moving the crop values to the config would be better. Because the user can set the size of the image in the dashcam, the script needs to check the image size. Percentages might work better using the config. I need to read up on how percentages work - it's something I hadn't see.

BTW - it's amazing you were able to follow my script. I kludged it together over a period of a few weeks.

Also, I should add it's nice hearing from you. It's been a while.

**Comment by mackerski** [comment]
It sure is nice to be back in touch. Hope you're well!

I want to avoid stealing any valour on the area of having insight into the script. I'm not much of a shell guy, and I won't claim to have gained a handle on all of what's in there. I chased down the quoting issues iteratively and then faffed around with the ffmpeg call. I won't offer any update on that until I can suggest something that can accommodate the needs of other users and not just mine. But I have an idea of how to put in a config item certainly for jpeg encoding quality, but hopefully also for a version of cropping that can accommodate variable source frame dimensions.

Amusingly, I have so far not actually managed to upload any images, because I also have to wrestle with the tools from OSC and Mapillary. But I'm pleased to start by spending some time contributing to your efforts so that I can rely on a tool chain that is already in place and has somebody else who cares about it :)

**Comment by cliffordsnow** [comment]
You had me confused with the (it's the -r 1 part). I think you intended to say its the -qscale:v 1 part. 

I do see some improvement. I made the commit to include the qscale flag.

**Comment by mackerski** [comment]
You are completely correct, of course. I was careless, and named the other parameter with an argument of 1. As mentioned, I think I'll offer a patch to make the value of qscale come from config (unless you get there first).
